"""Initial Schema

Revision ID: c38135609fa6
Revises: 
Create Date: 2026-06-16 19:47:56.294581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38135609fa6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('zone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_camera', 'alerts', ['camera_id'], unique=False)
    op.create_index('ix_alert_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alert_timestamp', 'alerts', ['timestamp'], unique=False)
    op.create_index('ix_alert_type', 'alerts', ['detection_type'], unique=False)
    op.create_foreign_key(None, 'alerts', 'cameras', ['camera_id'], ['id'])
    op.create_index('ix_event_alert', 'detection_events', ['alert_id'], unique=False)
    op.create_index('ix_event_timestamp', 'detection_events', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'detection_events', 'alerts', ['alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_events', type_='foreignkey')
    op.drop_index('ix_event_timestamp', table_name='detection_events')
    op.drop_index('ix_event_alert', table_name='detection_events')
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index('ix_alert_type', table_name='alerts')
    op.drop_index('ix_alert_timestamp', table_name='alerts')
    op.drop_index('ix_alert_status', table_name='alerts')
    op.drop_index('ix_alert_camera', table_name='alerts')
    op.drop_table('cameras')
    # ### end Alembic commands ###
